name: Auto Update README

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC
  workflow_dispatch: # Lets you run it manually from Actions tab

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run update script
        run: |
          echo "Last updated on $(date)" > updated.txt
          # You can modify this to actually edit README.md instead of updated.txt
          sed -i "s|<!-- LAST_UPDATED -->.*|<!-- LAST_UPDATED --> $(date)|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated README update"
          git push
